# !!!! YOU NEED TO CHANGE THIS !!!!
# This is the connection string for your database
ConnStr = "dbname=gnorm-db host=127.0.0.1 sslmode=disable user=gnorm-user"

DBType = "postgres"

Schemas = ["public"]

PostRun = ["goimports", "-w", "$GNORMFILE"]

NameConversion = "{{pascal .}}"

# This will output the files in a subdirectory called "gnorm".  You can change
# this, but if you do, change the RootPkg definition below to match what the
# package name should be.
OutputDir = "gnorm"

[Params]
# RootPkg is the package declaration for the output dir. It should match the
# directory name above. You may change this as appropriate.
RootPkg = "gnorm"

# !!!! YOU NEED TO CHANGE THIS !!!!
# RootImport is the import path for the output directory.
RootImport = "gnorm.org/postgres-go/example/gnorm"

[SchemaPaths]
"fields.go" = "templates/fields.gotmpl"
"db.go" = "templates/db.gotmpl"

[TablePaths]
"{{toLower .Table}}/{{toLower .Table}}.go" = "templates/table.gotmpl"

[EnumPaths]
"enum/{{toLower .Enum}}.go" = "templates/enum.gotmpl"

[TypeMap]
"timestamp with time zone" = "time.Time"
"timestamptz" = "time.Time"
"varchar" = "string"
"text" = "string"
"boolean" = "bool"
# from "github.com/satori/go.uuid"
"uuid" = "uuid.UUID"
"character varying" = "string"
"character" = "string"
"integer" = "int"
"int4" = "int32"
"numeric" = "float64"
# from "github.com/lib/pq/hstore"
"hstore" = "hstore.Hstore"
# note that the package name here has to be kept in sync with the RootPkg above.
"jsonb" = "gnorm.Jsonb"
# the package name here needs to be kept in sync with the enum template's package name
"book_type" = "enum.BookType"


[NullableTypeMap]
"timestamp with time zone" = "pq.NullTime"
"text" = "sql.NullString"
"boolean" = "sql.NullBool"
"uuid" = "uuid.NullUUID"
"character varying" = "sql.NullString"
"character" = "sql.NullString"
"integer" = "sql.NullInt64"
"numeric" = "sql.NullFloat64"
"hstore" = "hstore.Hstore"
# note that the package name here has to be kept in sync with the RootPkg above.
"jsonb" = "gnorm.Jsonb"
